### ISSUE TITLE
TSLSocket issue with latest 2.1 API

### ISSUE THREAD

**Issue by egonw** [openphacts/ops.js#34]
When running 'npm test' on master/develop, I get the following error since the recent sever moves:

    > jasmine-node --captureExceptions --config app_id 1c22cbe7 --config app_key 167a3a3d8539b5d85280e7178f4e62ab --config app_url https://beta.openphacts.org/2.1 ./test/spec/integration/
    
    TypeError: Cannot read property 'statusCode' of undefined
        at Request._callback (/home/egonw/var/Projects/GitHub/ops.js/src/ActivitySearch.js:39:17)
        at self.callback     (/home/egonw/var/Projects/GitHub/ops.js/node_modules/request/request.js:187:22)
        at emitOne (events.js:96:13)
        at Request.emit (events.js:188:7)
        at Request.onRequestError (/home/egonw/var/Projects/GitHub/ops.js/node_modules/request/request.js:813:8)
        at emitOne (events.js:96:13)
        at ClientRequest.emit (events.js:188:7)
        at TLSSocket.socketErrorListener (_http_client.js:310:9)
        at emitOne (events.js:96:13)
        at TLSSocket.emit (events.js:188:7)
    npm ERR! Test failed.  See above for more details.

See also http://support.openphacts.org/support/tickets/165

**Comment by egonw** [comment]
Ideally, the code would catch the TLSSocket issue earlier and give a better error message. But the problem itself needs solving too.

**Comment by egonw** [comment]
Fixed upstream.
