### ISSUE TITLE
CompoundSearch needs updating for 2.2

### ISSUE THREAD

**Issue by egonw** [openphacts/ops.js#38]
```
TypeError: Cannot read property 'primaryTopic' of undefined
    at CompoundSearch.parseCompoundResponse (/home/egonw/var/Projects/GitHub/ops.js/src/CompoundSearch.js:366:23)
    at Request.callback (/home/egonw/var/Projects/GitHub/ops.js/test/spec/integration/CompoundIntegrationSpec.js:25:40)
    at Request._callback (/home/egonw/var/Projects/GitHub/ops.js/src/CompoundSearch.js:52:22)
    at Request.self.callback (/home/egonw/var/Projects/GitHub/ops.js/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/egonw/var/Projects/GitHub/ops.js/node_modules/request/request.js:1048:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/egonw/var/Projects/GitHub/ops.js/node_modules/request/request.js:969:12)
```

**Comment by ianwdunlop** [comment]
Might be looking for 'http://www.conceptwiki.org/concept/38932552-111f-4a4e-a46a-4ed1d7bdf9d5' which maybe doesn't exist any more in the store.
