### ISSUE TITLE
regressions with the 2.2 API

### ISSUE THREAD

**Issue by egonw** [openphacts/ops.js#42]
```
FFF..........................................F.................F...........................................

Failures:

  1) Activities get all units and return a response
   Message:
     Expected false to be true.
   Stacktrace:
     Error: Expected false to be true.
    at null.<anonymous> (/home/egonw/var/Projects/GitHub/ops.js/test/spec/integration/ActivityIntegrationSpec.js:94:30)
    at Timer.listOnTimeout (timers.js:92:15)

  2) Activities get all units and return a response
   Message:
     Expected 404 to be 200.
   Stacktrace:
     Error: Expected 404 to be 200.
    at null.<anonymous> (/home/egonw/var/Projects/GitHub/ops.js/test/spec/integration/ActivityIntegrationSpec.js:95:29)
    at Timer.listOnTimeout (timers.js:92:15)

  3) Activities get all units and return a response
   Message:
     TypeError: Cannot read property 'length' of null
   Stacktrace:
     TypeError: Cannot read property 'length' of null
    at null.<anonymous> (/home/egonw/var/Projects/GitHub/ops.js/test/spec/integration/ActivityIntegrationSpec.js:96:27)
    at Timer.listOnTimeout (timers.js:92:15)

  4) Activities get all units and handle errors
   Message:
     Expected 404 to equal 500.
   Stacktrace:
     Error: Expected 404 to equal 500.
    at null.<anonymous> (/home/egonw/var/Projects/GitHub/ops.js/test/spec/integration/ActivityIntegrationSpec.js:114:29)
    at Timer.listOnTimeout (timers.js:92:15)

  5) Concept Wiki free text search and return a response
   Message:
     timeout: timed out after 30000 msec waiting for something to happen
   Stacktrace:
     undefined

  6) Pathways interactions by entity and return a response
   Message:
     timeout: timed out after 30000 msec waiting for something to happen
   Stacktrace:
     undefined

  7) Structure search similarity and return a response
   Message:
     Expected false to equal true.
   Stacktrace:
     Error: Expected false to equal true.
    at null.<anonymous> (/home/egonw/var/Projects/GitHub/ops.js/test/spec/integration/StructureIntegrationSpec.js:200:30)
    at Timer.listOnTimeout (timers.js:92:15)

  8) Structure search similarity and return a response
   Message:
     Expected 404 to equal 200.
   Stacktrace:
     Error: Expected 404 to equal 200.
    at null.<anonymous> (/home/egonw/var/Projects/GitHub/ops.js/test/spec/integration/StructureIntegrationSpec.js:201:29)
    at Timer.listOnTimeout (timers.js:92:15)

  9) Structure search similarity and return a response
   Message:
     TypeError: Cannot read property 'length' of null
   Stacktrace:
     TypeError: Cannot read property 'length' of null
    at null.<anonymous> (/home/egonw/var/Projects/GitHub/ops.js/test/spec/integration/StructureIntegrationSpec.js:202:27)
    at Timer.listOnTimeout (timers.js:92:15)

Finished in 337.833 seconds
107 tests, 632 assertions, 9 failures, 0 skipped
```

**Comment by egonw** [comment]
Of course, there are various other reported issues around the 2.2 API which required commenting out the test, and that obviously also need fixing... see this commit:

https://github.com/openphacts/ops.js/compare/patch/api2.2?expand=1
